---
deployment:
  tasks:
    - export DEPLOYPATH=/home/puty1694/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sale.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH